### PR TITLE
Micro Reddit Ruby on Rails  Application

### PR DESCRIPTION
**Pull request by vikitaotiz**
I have created a basic blogging application using ruby on rails.
I have implemented the following concepts;

1. - Installation and configuration of ruby on rails.
2. - Followed MVC application architecture to implement CRUD operations
3. - I have created posts controller
4. - I have created routers
5. - I have created posts view files
6. - I have created post model
7. - I have configured Postgresql for both development and production

### CODE REVIEW

**Review by BrianSammit — COMMENTED** [review]
STATUS INVALID :yellow_circle: 
------
Hello, @vikitaotiz great job you are doing on this project. Friendly reminder: You should make sure that your repo looks professional before review. You don't have properly set up the linters checks. [Here](https://github.com/microverseinc/linters-config/tree/master/ror) you can have a reminder. 
Also, the default branch on GitHub must be the development branch. please change it. 

Once that's done please send it again for another review.

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] PR and commit messages are descriptive.
- [ ] README is professional and includes all the necessary info to run the project locally.

## To Improve 🙏
- [ ] Your app should allow creating a new user. You don't have a User model and associations for it. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingUser.png).
### User:
- [ ] Please add validations for username. See this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/userValidation.png).
- [ ] User has_many : posts. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/user_has_many_posts.png).
- [ ] User has_many :comments. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/user_has_many_comments.png).
### Post:
- [ ] Post belongs_to: user. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/post_belongs_to_a_user.png).
### Comment:
- [ ] Comment belongs_to : user. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/comment_belongs_to_a_user.png).
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Review by carlos-ssh — CHANGES_REQUESTED** [review]
Hello Team! 👋🏽👋🏽👋🏽
Your project is really great‼️

Please help me to fix this issue that I have when I try to run your project locally: 
Screen Shot 2021-06-07 at 05 47 48

Kindly add this instruction to your setup into your README file if it is necessary to do this step when somebody wants to run your project locally.

Happy Coding! 👾👨🏽‍💻
@Carlos-SSH

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️
@vikitaotiz WeldonE for the job done,however for this project to be approved few chages is required:
### Highlights
- [x]  Please add validations for username. 
- [x]  User has_many : posts. 
- [x]  User has_many :comments. 
- [x]  Post belongs_to: user. 
- [x]  Comment belongs_to : user. 
### Improve
- [ ] A post can be created **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingPost.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
getting this error
Screenshot 2021-06-07 182634

- [ ] A comment can be created **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingComment.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
## once specific changes made kindly request for another request

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @vikitaotiz ! :wave: :wave:

####  Good job for making all the necessary corrections recommended by the previous reviewer(s). 👏 . Your code looks good,  👍  Congratulations!  :clap:


#### You may merge, good luck with the next project! :rocket:

If you have any questions please feel free to drop me a comment.

#### Happy Coding! :+1:

__Robert Loterh __
[GitHub](https://github.com/rloterh) | [LinkedIn](https://www.linkedin.com/in/rloterh/) | [Twitter](https://twitter.com/RLoterh)

**Pull request merged**
